# Generated by Django 5.0.6 on 2024-06-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_credential_source_credential_credential_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='credential_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
