# Generated by Django 5.0.6 on 2024-06-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_credential_credential_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='credential',
            name='credential_password',
            field=models.CharField(max_length=512),
        ),
    ]
